### ISSUE TITLE
certs.domain.com; what type of container?

### ISSUE THREAD

**Issue by milovanderlinden** [Levino/letsencrypt-cert-service#7]
Hi Levino,

There is something I do not understand completely. In the Usage section on the readme, you talk about certs.domain.com. I have set up my DNS for a certs subdomain. But now there is something I do not understand. your letsencrypt image is running on a container that has the virtualhost set to 'VIRTUAL_HOST=http://_/.well-known/_' how do you add route that haproxy understands that will open up the certs.domain.com setup from your example?

for reference; this is a tutum stackfile I currently have:

``` yaml

haproxy:
  image: 'tutum/haproxy:latest'
  links:
    - 'myfirstapp'
    - 'mysecondapp'
    - 'mythirdapp'
    - letsencrypt
  ports:
    - '80:80'
    - '443:443'
  roles:
    - global
letsencrypt:
  image: 'levino/letsencrypt-cert-service:latest'
  environment:
    - 'CERT_DOMAINES=mydomain.something.nl,another.differentdomain.nl'
    - CERT_EMAIL=milo@_____.net
    - CERT_SERVICE_PASSWORD=somepasswordbutwaywaybetter
    - CERT_SERVICE_PRIVATE=true
    - CERT_SERVICE_USERNAME=milo
    - EXCLUDE_PORTS=443
    - 'VIRTUAL_HOST=http://*/.well-known/*'
    - VIRTUAL_HOST_WEIGHT=1
  volumes:
    - /etc/letsencrypt
```

Could you tell me what I am doing wrong? I will then help you to put the missing pieces in the documentation.

**Comment by levino** [comment]
You will have to add multiple virtual host names. Also dont forget that you want to issues certs for the "certs..." domain, so you can download the certificates through a properly encrypted connection.

``` yaml

haproxy:
  image: 'tutum/haproxy:latest'
  links:
    - 'myfirstapp'
    - 'mysecondapp'
    - 'mythirdapp'
    - letsencrypt
  ports:
    - '80:80'
    - '443:443'
  roles:
    - global
letsencrypt:
  image: 'levino/letsencrypt-cert-service:latest'
  environment:
    - 'CERT_DOMAINES=mydomain.something.nl,another.differentdomain.nl,certs.something.nl'
    - CERT_EMAIL=milo@_____.net
    - CERT_SERVICE_PASSWORD=somepasswordbutwaywaybetter
    - CERT_SERVICE_PRIVATE=true
    - CERT_SERVICE_USERNAME=milo
    - EXCLUDE_PORTS=443
    - 'VIRTUAL_HOST=http://*/.well-known/*,https://certs.something.nl,http://certs.something.nl'
    - VIRTUAL_HOST_WEIGHT=1
  volumes:
    - /etc/letsencrypt
```

And then put the host (or tutum dns) as a dns record for "certs.something.nl" and the traffic will end up in the container. That way you can reach it to start issuing the certificates. If you want to issue a certificate for "mydomain.something.nl" be sure to also put a dns entry for that entry in that directs to the haproxy.

Does this help?
