### ISSUE TITLE
Struggling to make it work

### ISSUE THREAD

**Issue by sslash** [Levino/letsencrypt-cert-service#9]
Struggling to set it up, here's my stackfile (tutum specific):

``` yaml
letsencrypt:
  image: 'levino/letsencrypt-cert-service:latest'
  environment:
    - 'CERT_DOMAINES=domain.guide,certs.domain.guide'
    - CERT_EMAIL=team@domain.guide
    - CERT_SERVICE_PASSWORD=secretsecret
    - CERT_SERVICE_PRIVATE=true
    - CERT_SERVICE_USERNAME=myuname
    - EXCLUDE_PORTS=443
    - 'VIRTUAL_HOST=http://*/.well-known/*,https://certs.domain.guide,http://certs.domain.guide'
    - VIRTUAL_HOST_WEIGHT=1
  volumes:
    - /etc/letsencrypt
load-balancer-staging:
  image: 'tutum/haproxy:latest'
  links:
    - node-blue
    - letsencrypt
  ports:
    - '80:80'
    - '443:443'
  roles:
    - global
node-blue:
  image: 'webapp-image'
  environment:
    - NODE_ENV=production
    - SERVER=true
    - 'VIRTUAL_HOST=domain.guide'
  ports:
    - '8000'
```

**Comment by levino** [comment]
`CERT_DOMAINS` not `CERT_DOMAINES`

Can you paste logs from the cert-service container?

**Comment by sslash** [comment]
letsencrypt-1 | 2016-02-11T19:13:11.769031599Z npm info it worked if it ends with ok
letsencrypt-1 | 2016-02-11T19:13:11.769532442Z npm info using npm@2.14.12
letsencrypt-1 | 2016-02-11T19:13:11.770303582Z npm info using node@v4.2.4
letsencrypt-1 | 2016-02-11T19:13:12.085206182Z npm info prestart letsencrypt-cert-service@0.1.0
letsencrypt-1 | 2016-02-11T19:13:12.090421271Z npm info start letsencrypt-cert-service@0.1.0
letsencrypt-1 | 2016-02-11T19:13:12.094726047Z 
letsencrypt-1 | 2016-02-11T19:13:12.094747280Z > letsencrypt-cert-service@0.1.0 start /usr/src/app
letsencrypt-1 | 2016-02-11T19:13:12.094758678Z > node ./start.js
letsencrypt-1 | 2016-02-11T19:13:12.094768247Z 
letsencrypt-1 | 2016-02-11T19:13:12.613974975Z {"name":"LetsEncrypt Cert Service","hostname":"letsencrypt-1","pid":25,"level":30,"msg":"Succeeded to start cert service","time":"2016-02-11T19:13:12.611Z","v":0}

**Comment by levino** [comment]
Did you change above env var? Still an issue?

**Comment by sslash** [comment]
jupp. getting 503 service unavailable when I try to go to haproxy url

**Comment by levino** [comment]
You should get a 404 from node-blue...

**Comment by levino** [comment]
Where is this deployed? Not under "domain.guide"

**Comment by sslash** [comment]
node-blue responds normally. Haproxy still gives me this:
"503 Service Unavailable
No server is available to handle this request."
Its not deployed under that domain, because this is just a sandbox environment I sat up to test if it works. When I tried it in production, I got the 503, so I would like to be a bit more confident it will work before I deploy the setup in production. At some point I'll point routes.guide to the sandbox environment (temporary to verify it works) but then I want to get rid of the 503 first

**Comment by levino** [comment]
I don't follow.

When you go to "http://domain.guide" node-blue answers?

When you go to "http://domain.guide/welcome" node-blue answers?

When you go to "http://domain.guide/.well-known/check" you a get a 503?

The node-blue should also answer in the last case if the cert service fails to answer.

**Comment by sslash** [comment]
Ah no no, every url always responds with 503. Thats why I took it down, and now I am trying the same setup on a different cluster. Still the haproxy url gives 503

**Comment by levino** [comment]
Okay. Tell me when you get "http://domain.guide" to work. This will mean that the loadbalancer - blue-node setup is working. Explaining how to achieve this is out of scope here.

I would guess that you are querying the ip where you deployed this like "http://123.142.24.11" but NOT "http://domain.guide". Querying the IP will NOT work. How should haproxy know where you wanna go? A workaround is to put the "domain.guide" host in your /etc/hosts to target to the above IP. Then you can go in the browser to "http://domain.guide" wich will be resolved to the aforementioned IP, WHILE telling the server that you are actually looking for "http://domain.guide".

BTW: The service can be risk added risk free to any production environment that has a working haproxy setup. Traffic will continue to be correctly routed. Your 503s above have nothing to do with adding a containter with my image. It is an issue of the overall setup.

**Comment by sslash** [comment]
My haproxy-express setup works well without this service. However when I add a link from haproxy to letsencrypt, and set VIRTUAL_HOST in the express definition, haproxy responds with a 503 (hitting the express server still responds normally)

**Comment by levino** [comment]
So just to clarify, the following works fine?

``` yaml
load-balancer-staging:
  image: 'tutum/haproxy:latest'
  links:
    - node-blue
  ports:
    - '80:80'
    - '443:443'
  roles:
    - global
node-blue:
  image: 'webapp-image'
  environment:
    - NODE_ENV=production
    - SERVER=true
    - 'VIRTUAL_HOST=domain.guide'
  ports:
    - '8000'
```

Could you paste the complete logs of the haproxy when you link the the cert service? It should show an indication of that it acknowledges to route traffic to the cert service to certs.domain.guide.

Could you deploy this stack under a real hostname / subdomain like "test.domain.guide"?
